# Generated by Django 3.2.25 on 2024-09-01 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('.jsx', 'JavaScript XML'), ('.css', 'Cascading Style Sheets')], max_length=10)),
                ('content', models.TextField(blank=True)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('expert', 'Expert')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('expert', 'Expert')], max_length=10)),
                ('files', models.ManyToManyField(to='components.ComponentFile')),
            ],
        ),
    ]
